apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP                      #ClusterIP is the default type. It exposes the service on a cluster-internal IP. Other options are nodePort, LoadBalancer, and ExternalName.
  selector:
    app: nginx                         #This selector will match the label of the pods created by the deployment
  ports:
    - protocol: TCP
      port: 80                          #Port on which the service will be exposed
      targetPort: 80                    #Port on which the pods are listening