flask:
  image: binyul11/github-actions-learn-demo2:14
  replicas: 2
  service:
    type: NodePort
    port: 5000
    nodePort: 30081

mysql:
  image: mysql:8.0
  database: mydb
  user: flaskuser
  password: flaskpass
  rootPassword: rootpass
  storage: 1Gi